### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by cartantino** [frhnfrq/MathView#2]
Hi, I am facing this issue importing your library
ERROR: Failed to resolve: com.github.frhnfrq:MathView:1.1

**Comment by frhnfrq** [comment]
Hello, make sure you have added the JitPack repository to your project level build.gradle file. Read the full guide here https://jitpack.io/#frhnfrq/MathView/1.1

**Comment by cartantino** [comment]
Thank you so much! That resolved it, and thanks for this great work

Best regards, 
Costantino
