### ISSUE TITLE
Use library with RecyclerView? 

### ISSUE THREAD

**Issue by SMIKLooK** [frhnfrq/MathView#4]
Hello! Hw can I use library with RecyclerView?

**Comment by SMIKLooK** [comment]
Haw excuse me

**Comment by SMIKLooK** [comment]
How excuse me

**Comment by SMIKLooK** [comment]
In onBindViewHolder write the whole MathView eg on Kotlin:

val item = dataset[position]
        holder.mathView.text = context.resources.getString(item.mathViewResourceStringId)
        holder.mathView.pixelScaleType = MathView.Scale.SCALE_DP
        holder.mathView.textColor = "#111111"
        holder.mathView.setTextSize(20)

**Comment by frhnfrq** [comment]
Hi, didn't understand your issue. You can use the MathView in your RecyclerView just like any other View. @SMIKLooK

**Comment by SMIKLooK** [comment]
Hello I already figured it out, I forgot to close the question, sorry.
